// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfatzpnkigmoqcqzdtkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYXR6cG5raWdtb3FjcXpkdGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTY3MTAsImV4cCI6MjA2MzIzMjcxMH0.NwHCKhzFAMWYYydzAuVFzv5lk6TvDxnSv_xEsIFn6TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
